version: 0.2
phases:
  build:
    commands:      
        
          aws s3 cp  s3://sftp-bucket-poswal091993/sftp-testuser-dev/index.html s3://sftp-bucket-poswal091993/qa/
             
  post_build:

    commands:

       - echo Build completed                 

