version: 0.2
phases:
  build:
    commands:      
        
          aws s3 cp  s3://sftp-bucket-poswal091993/dev/rmi.txt s3://sftp-bucket-poswal091993/qa/
             
  build2:

    commands:

      aws s3 cp  s3://sftp-bucket-poswal091993/qa/rmi.txt s3://sftp-bucket-poswal091993/al/                  

