version: 0.2

env:
  shell: shell-tag
  variables:
    path: "(now.format("yyyyMMdd") + "_OS_Update")"    
phases:
  build:
    commands:      
        
          aws s3 cp  s3://sftp-bucket-poswal091993/dev/index.html s3://sftp-bucket-poswal091993/qa/
             
  post_build:

    commands:

      aws s3 cp  s3://sftp-bucket-poswal091993/qa/index.html s3://sftp-bucket-poswal091993/al/"$path"'/'                

