version: 0.2
phases:
  build:
    commands :
        aws s3 cp --recursive s3://mybucketforstaticweb1212/dev/sgrover.txt s3://mybucketforstaticweb1212/qa/

  post_build:

    commands:

       - echo Build completed                      

