version: 0.2

phases:

  pre_build:
    commands: 
          # First Step is to removing existing folder in QA of previous build 
        -  aws s3 cp s3://qwdqwdqwd/index.html s3://mainbucketdest/ --source-region us-east-1 --region us-east-2
