version: 0.2
env:  
  variables: 
     #Set the date = current date and foldercomplete name 
     DATE=$(date +\%Y\%m\%d_OS_Update)
phases:

  pre_build:
    commands: 
          # First Step is to removing existing folder in QA of previous build 
        -  aws s3 cp s3://mainbucketsourceregion/index.html s3://mainbucketdest
